launch: revise data and config directory usage
- Set data and config directories for FieldWorks/liblcm and Encoding
Converters, according to usage and whether packaging for an Ubuntu
.deb package or a flatpak package.
- Don't make significant changes to where the Ubuntu .deb package
stores data or configs, or its startup behaviour. Primarily making the
changes for when running in flatpak.
- Added explanations of various paths in environ.
- Use environ earlier in run-app, so the settings are available in
setup-user. This allows `environ` to be a central place to define
locations.
- Rearranged the setup-user registry setting a bit. Importantly,
anything that made registry settings that included the PREFIX path
(like `/usr` or `/app`) was put down into the every-time section. The
setup-user "Set values unconditionally, to take care of upgrades"
dates back to FieldWorks 7.3.
- Removed the possibly misleading shebang at the top of environ, since
environ shouldn't be executed.
- environ: Selectively use `USER_DATA_HOME` (made up to help here) and
`XDG_DATA_HOME` (external standard) to specify where to save data and
configuration. The two variables will be the same value when running
from an Ubuntu .deb package (eg `~/.local/share`). But in flatpak,
they will differentiate between data stored in a user-specific area
outside of the flatpak (`USER_DATA_HOME`) and data stored in an
application-specific area inside the flatpak (`XDG_DATA_HOME`).
- FW projects continue to be used in a in user-specific area.
- Writing Systems will continue to be used in a user-specific area so
they can be shared with other applications (by setting USER_DATA_HOME,
that libpalaso 6 will start to pick up).
- Some files that end up in the application-specific location include
Geckofx/DefaultProfile, SIL/Language Explorer/DialogResponses.xml,
SIL/SIL FieldWorks/9.../user.config, CommonLocalizations/.../...xlf
- Add license headers. run-app and setup-user both date to 2010.
environ is from at least 2009, when it was copied into git from svn.

Change-Id: I0541bbb7393890e45daff41807603a70a2ad7d99

diff --git a/Lib/linux/run-app b/Lib/linux/run-app
--- a/Lib/linux/run-app
+++ b/Lib/linux/run-app
@@ -1,6 +1,10 @@
 #!/bin/bash
-
+#
 # Run a FieldWorks application
+#
+# Copyright (c) 2010 SIL International
+# This software is licensed under the LGPL, version 2.1 or later
+# (http://www.gnu.org/licenses/lgpl-2.1.html)
 
 [[ -z ${FW_DEBUG} ]] || set -x
 
@@ -8,62 +12,68 @@ scriptdir=$(dirname "$0")
 prefix=$(cd "$scriptdir/../.."; /bin/pwd)
 lib=$prefix/lib/fieldworks
 share=$prefix/share/fieldworks
-sharedWsRoot=/var/lib/fieldworks
-sharedWs=$sharedWsRoot/SIL/WritingSystemStore
+
+cd "$lib" && RUNMODE="INSTALLED" . environ && cd $OLDPWD
 
 # Usage: debug "foo baz" "bar"
 debug() {
   [[ -z ${FW_DEBUG} ]] || echo -e "$(date +'%F %T') run-app[$$]: " "$@"
 }
 
-# Test for write permissions in global writing system store.
-# If things are not set right, tell the user about it, erring on the side of
-# giving them more information than less, to help them solve it.
-# Test /var/lib/fieldworks not /var/lib/fieldworks/SIL/WritingSystemStore because the latter might not exist on the first run.
-# See FWNX-1420.
-# Note to power users: Upgrading Flex will result in permissions of the contents
-# of /var/lib/fieldworks being reset to being group-owned by fieldworks, g+w, and directories setgid,
-# as performed by fieldworks-applications.postinst.
-if [ $(find $sharedWsRoot -not -writable -print | wc -l) -gt 0 ]
-then
-	user_in_fieldworks_group_now="$(groups|grep -w fieldworks)"
-	user_in_fieldworks_group_at_all="$(id $(whoami) -Gn|grep -w fieldworks)"
-	additional_text=""
-	if [ -z "$user_in_fieldworks_group_now" -a -n "$user_in_fieldworks_group_at_all" ]; then
-		additional_text="It appears that this is the situation. Log out or reboot and then run FieldWorks again.
+if [[ -z ${FLATPAK_ID} ]]; then
+	# We are not running in flatpak. Use FW 9.0 deb package behaviour.
+	sharedWsRoot="/var/lib/fieldworks"
+	debug "Checking permissions on ${sharedWsRoot}"
 
-"
-	elif [ -z "$user_in_fieldworks_group_at_all" ]; then
-		additional_text="But it appears that your user account has not been added to the fieldworks group.
-"
-	elif [ -n "$user_in_fieldworks_group_now" ]; then
-		more_text="
-However, your user is correctly in the fieldworks group but there are still write-permission
-problems in $sharedWsRoot. Perhaps the permissions were customized after installation.
-If so, have your computer administrator log in and fix the permissions by launching Terminal
-and executing:
+	# Test for write permissions in global writing system store.
+	# If things are not set right, tell the user about it, erring on the side of
+	# giving them more information than less, to help them solve it.
+	# Test /var/lib/fieldworks not /var/lib/fieldworks/SIL/WritingSystemStore because the latter might not exist on the first run.
+	# See FWNX-1420.
+	# Note to power users: Upgrading Flex will result in permissions of the contents
+	# of /var/lib/fieldworks being reset to being group-owned by fieldworks, g+w, and directories setgid,
+	# as performed by fieldworks-applications.postinst.
+	if [ $(find $sharedWsRoot -not -writable -print | wc -l) -gt 0 ]
+	then
+		user_in_fieldworks_group_now="$(groups|grep -w fieldworks)"
+		user_in_fieldworks_group_at_all="$(id $(whoami) -Gn|grep -w fieldworks)"
+		additional_text=""
+		if [ -z "$user_in_fieldworks_group_now" -a -n "$user_in_fieldworks_group_at_all" ]; then
+			additional_text="It appears that this is the situation. Log out or reboot and then run FieldWorks again.
 
-    sudo dpkg-reconfigure fieldworks-applications"
+	"
+		elif [ -z "$user_in_fieldworks_group_at_all" ]; then
+			additional_text="But it appears that your user account has not been added to the fieldworks group.
+	"
+		elif [ -n "$user_in_fieldworks_group_now" ]; then
+			more_text="
+	However, your user is correctly in the fieldworks group but there are still write-permission
+	problems in $sharedWsRoot. Perhaps the permissions were customized after installation.
+	If so, have your computer administrator log in and fix the permissions by launching Terminal
+	and executing:
+
+			sudo dpkg-reconfigure fieldworks-applications"
+		fi
+
+		zenity --error --no-wrap --text="This software cannot be run.
+
+	Missing write permissions on essential files or directories in $sharedWsRoot.
+
+	If you just installed FieldWorks, or were just added to the fieldworks group,
+	you will receive this error until you log out or reboot.
+	${additional_text}If you have already tried logging out or rebooting, then you need to
+	have a computer administrator add your user to the fieldworks group. To do this, have the
+	computer administrator log in, launch Terminal, and execute the following command:
+
+			sudo adduser $(whoami) fieldworks
+	$more_text"
+		exit 1
 	fi
 
-	zenity --error --no-wrap --text="This software cannot be run.
-
-Missing write permissions on essential files or directories in $sharedWsRoot.
-
-If you just installed FieldWorks, or were just added to the fieldworks group,
-you will receive this error until you log out or reboot.
-${additional_text}If you have already tried logging out or rebooting, then you need to
-have a computer administrator add your user to the fieldworks group. To do this, have the
-computer administrator log in, launch Terminal, and execute the following command:
-
-    sudo adduser $(whoami) fieldworks
-$more_text"
-	exit 1
 fi
 
 "$share/setup-user"
 
-cd "$lib"; RUNMODE="INSTALLED" . environ; cd $OLDPWD
 # set the LANG enviroment variable according to the value of UserWs in the registry.
 # unfortunately, there doesn't seem to be a Mono registry access utility, so we'll
 # use XSLT.  This is needed for localizations to work with fontconfig.
