launch: Do not quit from trouble printing diagnostics
Sometimes the launch scripts complain about errors writing debugging output.

Change-Id: Ie29266480e7bf599315909d61c5d5a85d8face8d

diff --git a/Lib/linux/run-app b/Lib/linux/run-app
--- a/Lib/linux/run-app
+++ b/Lib/linux/run-app
@@ -17,7 +17,7 @@ cd "$lib" && RUNMODE="INSTALLED" . environ && cd $OLDPWD
 
 # Usage: debug "foo baz" "bar"
 debug() {
-  [[ -z ${FW_DEBUG} ]] || echo -e "$(date +'%F %T') run-app[$$]: " "$@"
+  [[ -z ${FW_DEBUG} ]] || echo -e "$(date +'%F %T') run-app[$$]: " "$@" || : "Do not fail from write error Broken pipe"
 }
 
 if [[ -z ${FLATPAK_ID} ]]; then
