launch: fail faster if problem in launcher scripts
- Require variables to be defined before use. Exit immediately
on errors.
- Modify some variable usage to still work, where we sometimes
intentionally use what might be an undefined variable.
- Removed using a LD_LIBRARY_PATH that was specifically unset.

Change-Id: Icf9efefd2e7c60cce4d743caa87821a959ebc8f4

diff --git a/Lib/linux/run-app b/Lib/linux/run-app
--- a/Lib/linux/run-app
+++ b/Lib/linux/run-app
@@ -6,7 +6,9 @@
 # This software is licensed under the LGPL, version 2.1 or later
 # (http://www.gnu.org/licenses/lgpl-2.1.html)
 
-[[ -z ${FW_DEBUG_BASH_TRACE} ]] || set -x
+set -ueo pipefail
+
+[[ -z ${FW_DEBUG_BASH_TRACE-} ]] || set -x
 
 scriptdir=$(dirname "$0")
 prefix=$(cd "$scriptdir/../.."; /bin/pwd)
@@ -17,10 +19,10 @@ cd "$lib" && RUNMODE="INSTALLED" . environ && cd $OLDPWD
 
 # Usage: debug "foo baz" "bar"
 debug() {
-  [[ -z ${FW_DEBUG} ]] || echo -e "$(date +'%F %T') run-app[$$]: " "$@" || : "Do not fail from write error Broken pipe"
+  [[ -z ${FW_DEBUG-} ]] || echo -e "$(date +'%F %T') run-app[$$]: " "$@" || : "Do not fail from write error Broken pipe"
 }
 
-if [[ -z ${FLATPAK_ID} ]]; then
+if [[ -z ${FLATPAK_ID-} ]]; then
 	# We are not running in flatpak. Use FW 9.0 deb package behaviour.
 	sharedWsRoot="/var/lib/fieldworks"
 	debug "Checking permissions on ${sharedWsRoot}"
@@ -89,6 +91,6 @@ fi
 cd "$share" # Temporary
 # If set, use externally specified commands and args to launch with a debugger.
 # Otherwise just exec with mono.
-command="${FW_COMMAND_PREFIX} ${FW_MONO_COMMAND:-mono} ${FW_MONO_OPTS} --debug ""$lib"/"$@"
+command="${FW_COMMAND_PREFIX-} ${FW_MONO_COMMAND:-mono} ${FW_MONO_OPTS-} --debug ""$lib"/"$@"
 debug "Executing ${command} from dir $(pwd) in the following environment:\n$(env)"
 exec ${command}
diff --git a/Lib/linux/setup-user b/Lib/linux/setup-user
--- a/Lib/linux/setup-user
+++ b/Lib/linux/setup-user
@@ -9,9 +9,11 @@
 # See http://standards.freedesktop.org/basedir-spec/basedir-spec-0.6.html for
 # standard locations and environment variables.
 
-[[ -z ${FW_DEBUG_BASH_TRACE} ]] || set -x
+set -ueo pipefail
+
+[[ -z ${FW_DEBUG_BASH_TRACE-} ]] || set -x
 debugVerboseFlag=""
-[[ -z ${FW_DEBUG} ]] || debugVerboseFlag="-v"
+[[ -z ${FW_DEBUG-} ]] || debugVerboseFlag="-v"
 
 scriptdir="$(dirname "$0")"
 prefix=$(cd "$scriptdir/../.."; /bin/pwd)
@@ -26,7 +28,7 @@ READKEY="${FW_LIB}/ReadKey.exe"
 # Usage: Debug "blah blah" "blah"
 Debug()
 {
-	[[ -z ${FW_DEBUG} ]] || echo -e "$(date +'%F %T') setup-user[$$]: " "$@" || : "Do not fail from write error Broken pipe"
+	[[ -z ${FW_DEBUG-} ]] || echo -e "$(date +'%F %T') setup-user[$$]: " "$@" || : "Do not fail from write error Broken pipe"
 }
 
 Debug "FW_DATA: ${FW_DATA}"
@@ -73,7 +75,7 @@ CopyRegistryKey()
 		cp ${debugVerboseFlag} -a "${FW_SHARE}/Icu54" "${FW_CONFIG_DIR}/"
 	fi
 
-	if [[ -z ${FLATPAK_ID} ]]; then
+	if [[ -z ${FLATPAK_ID-} ]]; then
 		if [ ! -d "${FW_CONFIG_DIR}/SIL/" ]; then
 			# This stanza goes back to 2013, and may not still be significant.
 			echo "# Copying encoding converter registry"
